import type { Contract } from '../types';
// Canonical, immutable fictional source corpus. Page boundaries are editorially defined.
export const contracts: Contract[] = [
  {
    documentId: 'acme',
    filename: 'Acme Enterprise Agreement',
    shortName: 'Acme',
    effectiveDate: 'January 1, 2026',
    pages: 4,
    chunks: [
      {
        documentId: 'acme',
        filename: 'Acme Enterprise Agreement',
        page: 1,
        section: '1. Parties & scope',
        text: 'This fictional Enterprise Agreement takes effect on January 1, 2026 between Acme Systems Ltd. (Provider) and Harborline Design Co. (Customer). Provider grants Customer a nonexclusive right to use its hosted workflow platform for internal business operations, for up to 100 named users. The subscription includes reporting, workspace administration and standard onboarding. Customer retains ownership of its business records and is responsible for authorized users. Affiliates may participate only with written approval. This agreement and its four pages constitute the entire commercial arrangement; no additional order form changes the terms stated here. All names, services and signatures in this document are fictional and supplied solely for demonstration.',
        sourceId: 'acme-p1-parties',
      },
      {
        documentId: 'acme',
        filename: 'Acme Enterprise Agreement',
        page: 1,
        section: '2. Initial term & delivery',
        text: 'The initial subscription runs for twelve months, from January 1 through December 31, 2026. Provider will provision access within five business days of the effective date and supply two remote onboarding sessions during the first month. Customer will nominate an administrator and provide reasonable configuration instructions. Failure to attend an onboarding session does not postpone the subscription term. Material changes to the service description require written agreement by both parties. Routine product improvements may be released during the term, provided that they do not materially reduce the purchased functionality. Renewal and nonrenewal are governed by Section 6 on page 3.',
        sourceId: 'acme-p1-term',
      },
      {
        documentId: 'acme',
        filename: 'Acme Enterprise Agreement',
        page: 2,
        section: '3. Fees & payment',
        text: 'The subscription price is USD 24,000 per year, invoiced in twelve monthly installments of USD 2,000 in advance. Each invoice is payable within thirty calendar days of receipt (Net 30). Prices exclude applicable sales taxes. Customer may dispute an invoice in writing within fifteen days of receipt, describing the contested amount; undisputed amounts remain payable on time. The parties will work in good faith to resolve disputes within thirty days. Provider may charge simple interest of 1% per month on undisputed overdue balances, subject to applicable limits. No setup fee or mandatory minimum usage charge applies. Fees remain fixed throughout each annual term.',
        sourceId: 'acme-p2-payment',
      },
      {
        documentId: 'acme',
        filename: 'Acme Enterprise Agreement',
        page: 2,
        section: '4. Suspension & invoice remedies',
        text: "Provider may suspend access for an undisputed invoice more than fifteen days overdue only after giving Customer a further ten calendar days of written notice and an opportunity to pay. Suspension will be limited to the affected account and lifted promptly after payment. Provider may not suspend the service for amounts subject to a documented good-faith dispute. Customer remains responsible for subscription fees during a valid payment-related suspension. Provider will preserve Customer data throughout suspension. Credits resulting from Provider's SLA failures are applied to the next invoice and cannot be offset against taxes. Neither party may change bank details solely by an unauthenticated support message.",
        sourceId: 'acme-p2-suspension',
      },
      {
        documentId: 'acme',
        filename: 'Acme Enterprise Agreement',
        page: 3,
        section: '5. Termination & cancellation',
        text: "Either party may terminate for convenience by giving at least sixty calendar days of written notice. Termination for convenience takes effect at the end of the current annual term, not sixty days after notice if that date is earlier. Nonrenewal also requires sixty days' notice before the annual anniversary. Either party may terminate for a material breach that remains uncured thirty days after written notice identifying the breach. If Customer terminates because of Provider's uncured material breach, Provider will refund prepaid fees covering the unused service period. Convenience cancellation does not entitle Customer to an early exit or refund, and monthly installments remain due through the term's end.",
        sourceId: 'acme-p3-termination',
      },
      {
        documentId: 'acme',
        filename: 'Acme Enterprise Agreement',
        page: 3,
        section: '6. Renewal & price changes',
        text: 'At the end of the initial term, the subscription automatically renews for successive twelve-month terms unless either party gives the written nonrenewal notice required by Section 5. For the term ending December 31, 2026, notice must be received at least sixty calendar days before that date. Provider may increase renewal pricing by no more than 5% and must notify Customer at least ninety days before renewal. If Provider misses that pricing notice deadline, current pricing continues for the next renewal term. A renewal creates a new annual commitment even though invoices remain monthly. Notice must be sent to the contract administrator designated by each party.',
        sourceId: 'acme-p3-renewal',
      },
      {
        documentId: 'acme',
        filename: 'Acme Enterprise Agreement',
        page: 4,
        section: '7. Liability & indemnities',
        text: "Each party's aggregate liability arising from this agreement is capped at the fees paid or payable during the twelve months immediately preceding the event giving rise to the claim. At the initial subscription rate, this cap is USD 24,000. Neither party is liable for indirect, consequential, special or punitive damages, including lost profits. The cap and excluded-damage rule do not apply to fraud, willful misconduct or Customer's obligation to pay agreed subscription fees. Provider will defend third-party intellectual-property claims relating to the unmodified platform, subject to this same twelve-month cap. No separate uncapped confidentiality or data-security indemnity is created by this agreement.",
        sourceId: 'acme-p4-liability',
      },
      {
        documentId: 'acme',
        filename: 'Acme Enterprise Agreement',
        page: 4,
        section: '8. Service levels & data return',
        text: "Provider commits to 99.9% monthly service availability, excluding scheduled maintenance of up to four hours per month with forty-eight hours' notice, Customer-caused incidents and force majeure. Availability below 99.9% but at least 99% earns a credit of 5% of that month's subscription fee; availability below 99% earns 10%. Customer must request credits within thirty days of month-end. Credits are the sole remedy for an isolated SLA miss, without limiting termination for an uncured material breach under Section 5. Critical incidents receive an initial response within four business hours. Customer may export its data for thirty days after termination; Provider deletes remaining copies within sixty days, except required records.",
        sourceId: 'acme-p4-sla',
      },
    ],
  },
  {
    documentId: 'nova',
    filename: 'NovaCloud Services Agreement',
    shortName: 'NovaCloud',
    effectiveDate: 'February 1, 2026',
    pages: 4,
    chunks: [
      {
        documentId: 'nova',
        filename: 'NovaCloud Services Agreement',
        page: 1,
        section: '1. Parties & services',
        text: 'This fictional Services Agreement is made effective February 1, 2026 by NovaCloud Technologies Inc. (Provider) and Harborline Design Co. (Customer). Provider supplies hosted compute workspaces, collaboration tools, standard monitoring and up to 100 user seats. Customer may use the service only for its internal operations and must not resell access. Customer owns submitted business records. Provider may engage subprocessors while remaining responsible for delivery of the contracted services. This four-page agreement is the complete fictional source of the commercial terms used in the demonstration. No statement in this contract describes a real customer relationship, vendor commitment or actual legal obligation.',
        sourceId: 'nova-p1-parties',
      },
      {
        documentId: 'nova',
        filename: 'NovaCloud Services Agreement',
        page: 1,
        section: '2. Subscription commitment',
        text: "The initial term begins February 1, 2026 and ends January 31, 2027. Provider will make the workspace available within three business days after the effective date. Customer's minimum commitment is one full annual term even though monthly invoicing is offered. Additional seats require an agreed order and are excluded from the base price. Customer must maintain appropriate account security and promptly report unauthorized access. Provider may update nonmaterial features without consent, but removal of a core contracted function requires thirty days' written notice. Commercial changes, renewal dates and termination rights are controlled by Sections 3, 5 and 6 of this agreement.",
        sourceId: 'nova-p1-term',
      },
      {
        documentId: 'nova',
        filename: 'NovaCloud Services Agreement',
        page: 2,
        section: '3. Charges & payment deadline',
        text: "Customer will pay USD 36,000 per year in monthly invoices of USD 3,000 issued in advance. Payment is due within fifteen calendar days after the invoice date (Net 15), regardless of when Customer internally approves the invoice. Applicable taxes are additional. Customer must raise an invoice dispute within seven days and must pay the full invoiced amount while that dispute is resolved; valid adjustments will be credited later. Undisputed overdue amounts accrue simple interest at 1.5% per month, subject to applicable limits. Provider may require an annual prepayment after two late payments in any rolling six-month period. No prepaid subscription fees are refundable except for termination caused by Provider's uncured material breach.",
        sourceId: 'nova-p2-payment',
      },
      {
        documentId: 'nova',
        filename: 'NovaCloud Services Agreement',
        page: 2,
        section: '4. Service suspension',
        text: "Provider may suspend Customer's entire workspace once any invoiced amount is five calendar days overdue, after two business days' written warning. A pending invoice dispute does not itself prevent suspension because Section 3 requires payment during disputes. Subscription fees continue during payment-related suspension, and restoring service may take up to two business days after cleared payment. Provider will retain data for thirty days during suspension. Provider may also suspend access immediately to contain a credible security threat, with notice as soon as practical. Customer is responsible for keeping contact and billing details current. This clause does not shorten the initial annual subscription commitment or waive remaining fees.",
        sourceId: 'nova-p2-suspension',
      },
      {
        documentId: 'nova',
        filename: 'NovaCloud Services Agreement',
        page: 3,
        section: '5. Termination & early cancellation',
        text: "Either party may prevent renewal by giving at least thirty calendar days' written notice before the current annual term ends. This thirty-day period is a nonrenewal deadline, not a right to cancel an annual commitment without charge. Customer may cancel for convenience during a term on thirty days' written notice, but must immediately pay all remaining monthly fees for the balance of that term as an early cancellation charge. Either party may terminate for material breach that is not cured within fifteen days after written notice. If Provider's uncured material breach causes termination, unused prepaid fees are refunded and no early cancellation charge applies. Provider may terminate immediately for repeated unlawful service use.",
        sourceId: 'nova-p3-termination',
      },
      {
        documentId: 'nova',
        filename: 'NovaCloud Services Agreement',
        page: 3,
        section: '6. Automatic renewal',
        text: "This agreement automatically renews for additional twelve-month terms unless valid nonrenewal notice under Section 5 is received at least thirty days before the current term ends. Missing the notice deadline commits Customer to the entire next annual term. Provider may increase the renewal price by up to 12% with forty-five days' advance notice. Customer must still deliver timely nonrenewal notice if it rejects that increase; silence is acceptance of the renewal price. Monthly billing does not convert the subscription to a monthly contract. Changes to Customer's procurement process or budget do not excuse renewal fees. The first annual renewal would begin February 1, 2027.",
        sourceId: 'nova-p3-renewal',
      },
      {
        documentId: 'nova',
        filename: 'NovaCloud Services Agreement',
        page: 4,
        section: '7. Liability allocation & indemnity',
        text: "Provider's aggregate liability is capped at fees paid during the three months before the event giving rise to a claim, equivalent to USD 9,000 at the initial monthly rate. Customer's aggregate liability is capped at twenty-four months of subscription fees, equivalent to USD 72,000 at the initial rate. Customer's obligations for confidentiality breaches, data misuse and third-party claims arising from Customer content are expressly uncapped. Each party excludes indirect or consequential damages, except for Customer's indemnity obligations, fraud or willful misconduct. Provider's intellectual-property defense obligation remains within Provider's three-month cap. These are asymmetric liability caps: the Customer cap must not be described as protection supplied by Provider.",
        sourceId: 'nova-p4-liability',
      },
      {
        documentId: 'nova',
        filename: 'NovaCloud Services Agreement',
        page: 4,
        section: '8. Availability & offboarding',
        text: "Provider targets 99.5% monthly availability, excluding scheduled maintenance up to eight hours per month, upstream carrier failures, Customer-caused incidents and force majeure. If measured availability is below 99.5%, Customer may claim a credit equal to 5% of the affected month's subscription fee. Credits are capped at that 5% amount and must be requested within seven days of month-end. Service credits are the exclusive remedy for availability failures; repeated SLA misses do not create an additional termination right unless they independently amount to material breach under Section 5. Critical support requests receive an initial response within one business day. Customer has fourteen days after termination to export data before routine deletion begins.",
        sourceId: 'nova-p4-sla',
      },
    ],
  },
  {
    documentId: 'apex',
    filename: 'Apex Software Agreement',
    shortName: 'Apex',
    effectiveDate: 'March 1, 2026',
    pages: 4,
    chunks: [
      {
        documentId: 'apex',
        filename: 'Apex Software Agreement',
        page: 1,
        section: '1. Parties & license',
        text: "This fictional Software Agreement takes effect March 1, 2026 between Apex Software Cooperative (Provider) and Harborline Design Co. (Customer). Provider licenses its hosted project-planning application for Customer's internal operations for up to 100 users. The service includes administration controls, CSV export, standard support and three onboarding sessions. Customer retains all ownership in uploaded records. Provider retains ownership in the application and grants access for the duration of the subscription. Neither party may use the other's marks publicly without written permission. The parties and commercial relationship are fictional. These four source pages are authored for a portfolio demonstration and are not an executed legal instrument.",
        sourceId: 'apex-p1-parties',
      },
      {
        documentId: 'apex',
        filename: 'Apex Software Agreement',
        page: 1,
        section: '2. Initial term & transition',
        text: "The initial term lasts three months, from March 1 through May 31, 2026. Provider will provision the service within five business days and assist Customer's administrator with setup. After the initial term the agreement continues in successive monthly periods under Section 6; there is no new annual minimum. The cancellation notice period in Section 5 still applies during monthly renewals and may cause up to three additional months of fees after notice. Customer may add seats through a separate written amendment; no extra seats are assumed in this agreement. Provider may update the software provided essential planning and export functions remain available.",
        sourceId: 'apex-p1-term',
      },
      {
        documentId: 'apex',
        filename: 'Apex Software Agreement',
        page: 2,
        section: '3. Price & Net 45 terms',
        text: 'The service costs USD 1,500 per month, equivalent to USD 18,000 for twelve months of uninterrupted use. The annualized amount is a comparison figure, not an annual commitment. Provider invoices monthly in arrears. Customer must pay undisputed invoices within forty-five calendar days of receipt (Net 45). Taxes are additional. Customer may dispute an amount within thirty days of receipt and withhold only the disputed portion while the parties investigate in good faith. Simple interest of 0.5% per month applies to undisputed sums more than fifteen days beyond the due date, subject to applicable limits. No annual prepayment, onboarding fee or separate cancellation penalty is charged.',
        sourceId: 'apex-p2-payment',
      },
      {
        documentId: 'apex',
        filename: 'Apex Software Agreement',
        page: 2,
        section: '4. Payment cure & continuity',
        text: "Provider may suspend access only when an undisputed amount remains unpaid thirty calendar days after its due date and after an additional fifteen calendar days' written cure notice. Good-faith disputed balances cannot trigger suspension. Provider will restrict only the accounts reasonably necessary and keep data export available during a payment suspension. Service will resume within one business day of payment. Billing continues for contracted periods until termination takes effect. An unresolved billing dispute must be escalated to each party's contract administrator before suspension. Security-related restrictions may be applied immediately where necessary to contain active harm, with a written explanation and restoration plan within one business day.",
        sourceId: 'apex-p2-suspension',
      },
      {
        documentId: 'apex',
        filename: 'Apex Software Agreement',
        page: 3,
        section: '5. Termination & cancellation notice',
        text: "Either party may terminate for convenience by giving ninety calendar days' written notice. Termination takes effect on the last day of the monthly service period in which that notice period expires, but never before the initial three-month term ends. Customer pays normal monthly fees through the effective termination date; there is no accelerated annual balance or separate early cancellation fee. Any prepaid fees covering periods after that date must be refunded. Either party may terminate for material breach remaining uncured thirty days after written notice. Customer may also terminate without further commitment if the availability commitment is missed in three consecutive months. The ninety-day notice is longer than the renewal period and remains binding during month-to-month renewal.",
        sourceId: 'apex-p3-termination',
      },
      {
        documentId: 'apex',
        filename: 'Apex Software Agreement',
        page: 3,
        section: '6. Month-to-month renewal',
        text: "Following May 31, 2026, the service automatically renews for successive one-month periods until termination becomes effective under Section 5. Renewal does not create an annual obligation. Provider must give at least one hundred twenty days' written notice of a price increase, and increases may not exceed 3% in any twelve-month period. Customer can give its ninety-day cancellation notice after receiving a price-change notice, though termination remains aligned to a monthly period-end. If an increase would otherwise take effect before timely cancellation is effective, the prior price applies through cancellation. Notices are delivered in writing to designated contract administrators and are effective on confirmed receipt.",
        sourceId: 'apex-p3-renewal',
      },
      {
        documentId: 'apex',
        filename: 'Apex Software Agreement',
        page: 4,
        section: '7. Mutual limits & protections',
        text: "Each party's aggregate liability is capped at fees paid or payable during the six months before the event giving rise to the claim, equivalent to USD 9,000 at the initial monthly rate. Neither party is liable for consequential, incidental or punitive damages, including lost profits. Fraud, willful misconduct and Customer's obligation to pay agreed fees are outside these limits. Confidentiality, data-security and intellectual-property indemnity claims remain within the mutual six-month cap; there are no additional uncapped Customer-content indemnities. Provider will defend claims that the unmodified application infringes third-party intellectual property within that cap. The comparatively low cap also limits Customer's recovery from Provider; it should not be treated as an unqualified benefit to Customer.",
        sourceId: 'apex-p4-liability',
      },
      {
        documentId: 'apex',
        filename: 'Apex Software Agreement',
        page: 4,
        section: '8. SLA & transition assistance',
        text: "Provider commits to 99.95% monthly availability, excluding scheduled maintenance of up to two hours per month with seventy-two hours' notice, Customer-caused outages and force majeure. Availability below 99.95% but at least 99.5% earns a 10% monthly-fee credit; below 99.5% earns 20%. Credits must be requested within thirty days of month-end and are capped at 20% of the affected month's fee. Missing the commitment for three consecutive months permits Customer's termination under Section 5. Critical incidents receive an initial response within one business hour. Customer receives sixty days of read-only export access after termination at no extra fee. Provider deletes remaining data within ninety days, except records required by law.",
        sourceId: 'apex-p4-sla',
      },
    ],
  },
];
export const allChunks = contracts.flatMap((d) => d.chunks);
